#SPDX-License-Identifier: MIT-0
---
# tasks file for ec2
- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "ansible-collections"
    #key_name: "{{pem-ssh-key}}"
    vpc_subnet_id: subnet-0438f7642935300f6
    instance_type: t2.micro
    security_group: default
    region: us-east-1
    aws_access_key: "{{ec2_access_key}}" # From vault as defined
    aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined
    network_interfaces:
      - assign_public_ip: true
    image_id: ami-020cba7c55df1f615
